In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
#data cleaning cell

#import team and player dataframes

tdf = pd.read_csv('team_data_clean.txt', dtype = tdf_types)
tdf['GAME_DATE'] = pd.to_datetime(tdf['GAME_DATE'], format='%m/%d/%Y')

pdf = pd.read_csv('player_data_clean.txt')
pdf['GAME_DATE'] = pd.to_datetime(pdf['GAME_DATE'], format='%m/%d/%Y')
#pdf.to_csv('team_data_clean_v2.csv', index=False)

In [3]:
tdf = pd.read_csv('team_data_clean_v2.csv')
pdf = pd.read_csv('player_data_clean_v2.csv')

In [26]:
#line up home and away teams so there is 1 row for each game
homedf = tdf.loc[tdf['MATCHUP'].str.contains('vs')]

home_dict = dict(zip(homedf.columns, [x + '_home' for x in homedf.columns]))

homedf = homedf.rename(columns=home_dict).drop(columns='MATCHUP_home')
homedf

,TEAM_home,GAME_DATE_home,W/L_home,MIN_home,PTS_home,FGM_home,FGA_home,FG%_home,3PM_home,3PA_home,...,FT%_home,OREB_home,DREB_home,REB_home,AST_home,STL_home,BLK_home,TOV_home,PF_home,+/-_home
1,HOU,2021-12-03,W,240,118,44,93,47.3,17,47,...,86.7,8,28,36,33,7,5,12,16,2
2,ATL,2021-12-03,L,240,96,31,75,41.3,10,28,...,80.0,11,36,47,20,5,3,16,20,-2
4,BKN,2021-12-03,W,240,110,36,77,46.8,6,23,...,78.0,8,34,42,26,4,4,17,31,5
7,IND,2021-12-03,L,240,104,35,80,43.8,9,36,...,75.8,12,27,39,20,7,3,13,19,-9
8,WAS,2021-12-03,L,240,101,38,82,46.3,10,31,...,78.9,3,30,33,21,5,4,10,22,-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50491,ORL,2007-10-31,W,240,102,32,73,43.8,12,22,...,74.3,9,33,42,15,2,9,10,22,19
50492,NJN,2007-10-31,W,265,112,33,82,40.2,9,24,...,90.2,14,34,48,24,9,7,17,31,9
50495,LAL,2007-10-30,L,240,93,32,76,42.1,2,8,...,60.0,11,26,37,18,16,3,12,22,-2
50496,SAS,2007-10-30,W,240,106,41,87,47.1,6,24,...,69.2,12,28,40,21,8,4,9,19,9
50498,GSW,2007-10-30,L,240,96,32,77,41.6,6,23,...,68.4,7,30,37,19,8,9,20,28,-21

In [38]:
#line up home and away teams so there is 1 row for each game
awaydf = tdf.loc[~(tdf['MATCHUP'].str.contains('vs'))]

away_dict = dict(zip(awaydf.columns, [x + '_away' for x in awaydf.columns]))

awaydf['TEAM_home'] = awaydf['MATCHUP'].apply(lambda x: x[x.index('@_') + 2:])

awaydf = awaydf.rename(columns=away_dict)#.drop(columns='MATCHUP_away')
awaydf

C:\Users\jacob\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,TEAM_away,MATCHUP_away,GAME_DATE_away,W/L_away,MIN_away,PTS_away,FGM_away,FGA_away,FG%_away,3PM_away,...,OREB_away,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,+/-_away,TEAM_home
0,ORL,ORL_@_HOU,2021-12-03,L,240,116,42,86,48.8,13,...,10,35,45,24,6,5,18,21,-2,HOU
3,PHI,PHI_@_ATL,2021-12-03,W,240,98,38,81,46.9,9,...,6,33,39,22,9,4,11,24,2,ATL
5,MIN,MIN_@_BKN,2021-12-03,L,240,105,36,93,38.7,13,...,16,28,44,22,5,4,18,25,-5,BKN
6,MIA,MIA_@_IND,2021-12-03,W,240,113,43,81,53.1,16,...,9,29,38,24,5,6,13,22,9,IND
9,CLE,CLE_@_WAS,2021-12-03,W,240,116,42,89,47.2,13,...,15,39,54,30,2,5,16,19,15,WAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50490,MIL,MIL_@_ORL,2007-10-31,L,240,83,33,87,37.9,4,...,18,30,48,16,4,4,15,28,-19,ORL
50493,CHI,CHI_@_NJN,2007-10-31,L,265,103,38,96,39.6,8,...,19,26,45,23,7,3,16,30,-9,NJN
50494,HOU,HOU_@_LAL,2007-10-30,W,240,95,34,74,45.9,6,...,12,37,49,23,10,5,19,30,2,LAL
50497,POR,POR_@_SAS,2007-10-30,L,240,97,39,78,50.0,6,...,8,32,40,15,1,4,17,19,-9,SAS
50499,UTA,UTA_@_GSW,2007-10-30,W,240,117,41,90,45.6,5,...,16,40,56,24,9,7,19,26,21,GSW

In [51]:
#awaydf.rename(columns={'GAME_DATE_away': 'GAME_DATE_home'}, inplace=True)
#awaydf.columns, homedf.columns
homedf.drop_duplicates(inplace=True)
awaydf.drop_duplicates(inplace=True)

merged_df = homedf.merge(awaydf, on=['TEAM_home', 'GAME_DATE_home'])
merged_df

,TEAM_home,GAME_DATE_home,W/L_home,MIN_home,PTS_home,FGM_home,FGA_home,FG%_home,3PM_home,3PA_home,...,FT%_away,OREB_away,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,+/-_away
0,HOU,2021-12-03,W,240,118,44,93,47.3,17,47,...,90.5,10,35,45,24,6,5,18,21,-2
1,ATL,2021-12-03,L,240,96,31,75,41.3,10,28,...,76.5,6,33,39,22,9,4,11,24,2
2,BKN,2021-12-03,W,240,110,36,77,46.8,6,23,...,83.3,16,28,44,22,5,4,18,25,-5
3,IND,2021-12-03,L,240,104,35,80,43.8,9,36,...,84.6,9,29,38,24,5,6,13,22,9
4,WAS,2021-12-03,L,240,101,38,82,46.3,10,31,...,76.0,15,39,54,30,2,5,16,19,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16985,ORL,2007-10-31,W,240,102,32,73,43.8,12,22,...,59.1,18,30,48,16,4,4,15,28,-19
16986,NJN,2007-10-31,W,265,112,33,82,40.2,9,24,...,73.1,19,26,45,23,7,3,16,30,-9
16987,LAL,2007-10-30,L,240,93,32,76,42.1,2,8,...,67.7,12,37,49,23,10,5,19,30,2
16988,SAS,2007-10-30,W,240,106,41,87,47.1,6,24,...,76.5,8,32,40,15,1,4,17,19,-9
16989,GSW,2007-10-30,L,240,96,32,77,41.6,6,23,...,83.3,16,40,56,24,9,7,19,26,21

In [54]:
merged_df.to_csv('team_data_clean_v3.csv', index=False)

In [57]:
pdf.drop_duplicates(inplace=True)

In [59]:
pdf.to_csv('player_data_clean_v3.csv', index=False)